# Generated by Django 3.0.4 on 2020-03-23 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20200323_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='signout',
            field=models.DateTimeField(max_length=200, null=True),
        ),
    ]
