# Generated by Django 3.0.4 on 2020-03-24 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20200323_1624'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='time',
            new_name='Clocktime',
        ),
    ]
