# Generated by Django 3.0.4 on 2020-03-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_articles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='img',
        ),
        migrations.AddField(
            model_name='articles',
            name='image',
            field=models.ImageField(null=True, upload_to='logo'),
        ),
    ]
