# Generated by Django 3.0.4 on 2020-03-27 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_auto_20200327_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='avatar',
        ),
        migrations.AddField(
            model_name='articles',
            name='photo',
            field=models.ImageField(default='user1.jpg', upload_to='photos'),
        ),
    ]
