# Generated by Django 3.0.4 on 2020-03-27 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_auto_20200327_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='qq',
        ),
    ]
