# Generated by Django 3.0.4 on 2020-03-27 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_remove_customer_qq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='photo',
            field=models.ImageField(default='user1.jpg', null=True, upload_to='photos'),
        ),
    ]
