# Generated by Django 3.0.4 on 2020-03-27 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_auto_20200327_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos'),
        ),
    ]
