# Generated by Django 3.0.4 on 2020-04-16 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='password',
            new_name='branch',
        ),
        migrations.RemoveField(
            model_name='clocktime',
            name='signin',
        ),
        migrations.RemoveField(
            model_name='clocktime',
            name='signout',
        ),
        migrations.AddField(
            model_name='clocktime',
            name='code',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='staff',
            name='staff_number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unclockin_num', models.CharField(max_length=200)),
                ('leaveLength', models.CharField(max_length=200)),
                ('leavetime', models.DateTimeField(default='0', max_length=200)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.Staff')),
            ],
        ),
    ]
