# Generated by Django 3.0.4 on 2020-04-16 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_auto_20200416_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='staff',
        ),
    ]
