# Generated by Django 3.0.4 on 2020-04-16 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_remove_leave_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='clocktime',
            name='signin',
            field=models.DateTimeField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='clocktime',
            name='signout',
            field=models.DateTimeField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='clocktime',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.Staff'),
        ),
        migrations.AddField(
            model_name='clocktime',
            name='worktimes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.Staff'),
        ),
    ]
